### ISSUE TITLE
对 @cn 域名单独生成文件

### ISSUE THREAD

**Issue by ghost** [zydou/domain-list-community-converter#1]
@cn 单独出来后还是很灵活的。
具体请参考：https://github.com/Kr328/V2rayDomains2Clash/issues/5

**Comment by qeiypvg3q** [comment]
同样需要此功能，原本使用的规则列表同样支持此功能，同样使用domain-list-community生成，对@cn进行单独生成：
https://github.com/AkinoKaede/dlc2surge
https://raw.githubusercontent.com/AkinoKaede/dlc2surge/release/geolocation-!cn%2540cn.list
希望可以考虑增加！
